server:
  port: 8085

spring:
  datasource:
    druid:
      use-global-data-source-stat: true
      db-type: mysql
      url: jdbc:mysql://localhost:3306/lsp?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: newpassword
     # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
     # 配置监控统计拦截的filters，去掉后监控界面sql无法统计
      filters: stat,wall,slf4j,config
      initial-size: 3
      min-idle: 5
      max-active: 30
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
# druid监控配置
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "/druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico"
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
        # IP白名单(没有配置或者为空，则允许所有访问)
        #allow: 127.0.0.1,192.168.163.1
        # IP黑名单 (存在共同时，deny优先于allow)
        #deny: 192.168.1.73
        #禁用HTML页面上的“Reset All”功能
        reset-enable: true
        login-username: admin
        login-password: admin

      filter:
        config:
          enabled: true
        stat:
          log-slow-sql: true
          slow-sql-millis: 5000
          merge-sql: true
        slf4j:
          statement-executable-sql-log-enable: false
          statement-log-enabled: false
          result-set-log-enabled: false
        wall:
          # sql防火墙过滤器配置
          throw-exception: false
          log-violation: true
          # sql防火墙配置
          config:
            alter-table-allow: false
            create-table-allow: false
            delete-allow: false
            merge-allow: false
            describe-allow: false
            show-allow: false
      # aop配置
#      aop-patterns: com.seca.cfencing.core.modular.system.*.dao.*,com.seca.cfencing.core.modular.system.service.*








